# Generated by Django 5.0.3 on 2024-03-07 04:00

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourse', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='decription',
            field=ckeditor.fields.RichTextField(null=True),
        ),
    ]
